/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    institutes: Institute;
    departments: Department;
    teachers: Teacher;
    media: Media;
    users: User;
    submissions: Submission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    institutes: {
      departments: 'departments';
      staff: 'teachers';
    };
    departments: {
      staff: 'teachers';
    };
  };
  collectionsSelect: {
    institutes: InstitutesSelect<false> | InstitutesSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    teachers: TeachersSelect<false> | TeachersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('uk' | 'en') | ('uk' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'uk' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Institutes and the faculty. Each record is its own page; its list of departments is assembled automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutes".
 */
export interface Institute {
  id: number;
  name: string;
  /**
   * Auto-generated from the Ukrainian name. Avoid changing it after publishing — it breaks existing links.
   */
  slug: string;
  /**
   * Optional. The menu and the filters show the full name; this is kept for narrow placements and admin lists.
   */
  shortName?: string | null;
  /**
   * A smaller number sorts higher in the menu and on the homepage.
   */
  order?: number | null;
  /**
   * The background at the top of the institute page. Text sits over a darkened photo.
   */
  image?: (number | null) | Media;
  /**
   * Optional. The full-width band on the homepage. Falls back to the page image.
   */
  homepageImage?: (number | null) | Media;
  /**
   * The body of the page: About, specialities, the director's address (a pull-quote block), the directorate. The page header and the department list are added automatically and are not here.
   */
  about?:
    | (
        | RichTextBlock
        | PullQuoteBlock
        | VideoEmbedBlock
        | PillLinksBlock
        | StatsBandBlock
        | PersonCardBlock
        | StaffListBlock
        | ContactBlock
      )[]
    | null;
  contacts?: {
    address?: string | null;
    room?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  /**
   * Every department of this institute. The list in the page header is built from it — add a department and it appears in the menu.
   */
  departments?: {
    docs?: (number | Department)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Assembled automatically from everyone with an appointment at this institute. To add someone, open their record under Teachers and add an appointment.
   */
  staff?: {
    docs?: (number | Teacher)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for people who can't see it, and for search engines.
   */
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    portrait?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  /**
   * Shown to the left of the content. Leave empty and the section spans the full page width.
   */
  label?: string | null;
  /**
   * Formatting buttons are on the toolbar above the text.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Automatic: two columns with a heading, full width without one. "In the text column": when the block continues the section above and has no heading of its own.
   */
  width?: ('auto' | 'content' | 'full') | null;
  /**
   * Visitors can collapse and expand this section by clicking its heading.
   */
  collapsible?: boolean | null;
  /**
   * The section stays collapsed until a visitor clicks its heading.
   */
  collapsedByDefault?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PullQuoteBlock".
 */
export interface PullQuoteBlock {
  /**
   * Shown to the left of the content. Leave empty and the section spans the full page width.
   */
  label?: string | null;
  /**
   * Multiple paragraphs allowed. Formatting is bold and italic only.
   */
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  attribution?: string | null;
  /**
   * Automatic: two columns with a heading, full width without one. "In the text column": when the block continues the section above and has no heading of its own.
   */
  width?: ('auto' | 'content' | 'full') | null;
  /**
   * Visitors can collapse and expand this section by clicking its heading.
   */
  collapsible?: boolean | null;
  /**
   * The section stays collapsed until a visitor clicks its heading.
   */
  collapsedByDefault?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pullQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock".
 */
export interface VideoEmbedBlock {
  /**
   * Shown to the left of the content. Leave empty and the section spans the full page width.
   */
  label?: string | null;
  /**
   * The YouTube or Vimeo address, as it appears in the browser's address bar.
   */
  url: string;
  /**
   * Not shown on the page, but read out by screen readers.
   */
  title: string;
  /**
   * Automatic: two columns with a heading, full width without one. "In the text column": when the block continues the section above and has no heading of its own.
   */
  width?: ('auto' | 'content' | 'full') | null;
  /**
   * Visitors can collapse and expand this section by clicking its heading.
   */
  collapsible?: boolean | null;
  /**
   * The section stays collapsed until a visitor clicks its heading.
   */
  collapsedByDefault?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PillLinksBlock".
 */
export interface PillLinksBlock {
  /**
   * Shown to the left of the content. Leave empty and the section spans the full page width.
   */
  label?: string | null;
  /**
   * "This unit's specialities" builds the pills automatically from every speciality pointing at this institute or department. Only meaningful on an institute or department page.
   */
  source?: ('manual' | 'specialities') | null;
  /**
   * One pill per row. Drag to reorder.
   */
  items?:
    | {
        link?: {
          /**
           * Optional. Falls back to the target page's own title.
           */
          label?: string | null;
          type?: ('reference' | 'custom') | null;
          /**
           * Pick the type, then start typing a title. A document opens as a file.
           */
          reference?: {
            relationTo: 'institutes';
            value: number | Institute;
          } | null;
          url?: string | null;
          /**
           * Optional. Scrolls the page to the section with this id.
           */
          anchor?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Automatic: two columns with a heading, full width without one. "In the text column": when the block continues the section above and has no heading of its own.
   */
  width?: ('auto' | 'content' | 'full') | null;
  /**
   * Visitors can collapse and expand this section by clicking its heading.
   */
  collapsible?: boolean | null;
  /**
   * The section stays collapsed until a visitor clicks its heading.
   */
  collapsedByDefault?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pillLinks';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBandBlock".
 */
export interface StatsBandBlock {
  /**
   * Shown to the left of the content. Leave empty and the section spans the full page width.
   */
  label?: string | null;
  /**
   * "This unit's specialities" reads the codes and names of every speciality pointing at this institute or department. Only meaningful on their pages.
   */
  source?: ('manual' | 'specialities') | null;
  stats?:
    | {
        /**
         * Text rather than a number — it holds codes like "J5.01" as well as values like "80+".
         */
        value: string;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Automatic: two columns with a heading, full width without one. "In the text column": when the block continues the section above and has no heading of its own.
   */
  width?: ('auto' | 'content' | 'full') | null;
  /**
   * Visitors can collapse and expand this section by clicking its heading.
   */
  collapsible?: boolean | null;
  /**
   * The section stays collapsed until a visitor clicks its heading.
   */
  collapsedByDefault?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PersonCardBlock".
 */
export interface PersonCardBlock {
  /**
   * Shown to the left of the content. Leave empty and the section spans the full page width.
   */
  label?: string | null;
  /**
   * From the teacher directory. Photo, degree and position come from there — nothing is duplicated here.
   */
  teacher: number | Teacher;
  /**
   * Automatic: two columns with a heading, full width without one. "In the text column": when the block continues the section above and has no heading of its own.
   */
  width?: ('auto' | 'content' | 'full') | null;
  /**
   * Visitors can collapse and expand this section by clicking its heading.
   */
  collapsible?: boolean | null;
  /**
   * The section stays collapsed until a visitor clicks its heading.
   */
  collapsedByDefault?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'personCard';
}
/**
 * The staff directory. Cards on institute and department pages are built from it — add a person once, then appoint them to units.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers".
 */
export interface Teacher {
  id: number;
  fullName: string;
  /**
   * Auto-generated from the Ukrainian name. Unused for now — there are no teacher pages yet.
   */
  slug: string;
  /**
   * A portrait. Cropped to 3:4, so a vertical photo works best.
   */
  photo?: (number | null) | Media;
  /**
   * Belongs to the person rather than to a post, so it shows the same on every card.
   */
  degree?: string | null;
  email?: string | null;
  /**
   * Where the person works. Several units means several rows, each with its own position. A move is a change of unit on an existing row, not a new record.
   */
  appointments: {
    /**
     * A department or an institute. An institute appointment is administrative by definition.
     */
    unit:
      | {
          relationTo: 'institutes';
          value: number | Institute;
        }
      | {
          relationTo: 'departments';
          value: number | Department;
        };
    /**
     * Shown only on this unit's page. Positions differ between units.
     */
    position?: string | null;
    isPrimary?: boolean | null;
    /**
     * A smaller number sorts higher within the unit. Empty sorts alphabetically.
     */
    order?: number | null;
    id?: string | null;
  }[];
  /**
   * Optional. There are no teacher pages yet; this prepares the content for when there are.
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Institute departments. Each record produces seven pages — about, staff, research, disciplines, clubs, labs, news.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number;
  name: string;
  /**
   * Auto-generated from the Ukrainian name. The full address is the institute's plus this.
   */
  slug: string;
  /**
   * Decides the page address and which institute lists this department.
   */
  institute: number | Institute;
  /**
   * A smaller number sorts higher in the institute's list.
   */
  order?: number | null;
  /**
   * For departments that run a site of their own. The department page stays as it is; a link to that site appears at the top of the About tab.
   */
  externalUrl?: string | null;
  /**
   * Optional. The department artboards have no background photo — dark title on white.
   */
  image?: (number | null) | Media;
  /**
   * Rendered as its own block with a portrait. The person must exist in the teacher directory.
   */
  head?: (number | null) | Teacher;
  /**
   * The content of the first tab. The page header and the tab strip are added automatically.
   */
  about?:
    | (
        | RichTextBlock
        | PullQuoteBlock
        | VideoEmbedBlock
        | PillLinksBlock
        | StatsBandBlock
        | PersonCardBlock
        | StaffListBlock
        | ContactBlock
      )[]
    | null;
  /**
   * The tab's introductory text. The publication list itself becomes its own collection — 50 citations in one rich-text field can be neither searched nor paged.
   */
  research?:
    | (
        | RichTextBlock
        | PullQuoteBlock
        | VideoEmbedBlock
        | PillLinksBlock
        | StatsBandBlock
        | PersonCardBlock
        | StaffListBlock
        | ContactBlock
      )[]
    | null;
  clubs?:
    | {
        name: string;
        description?: string | null;
        supervisor?: (number | null) | Teacher;
        id?: string | null;
      }[]
    | null;
  labs?:
    | {
        name: string;
        description?: string | null;
        image?: (number | null) | Media;
        equipment?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  contacts?: {
    address?: string | null;
    room?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  /**
   * Assembled from appointments. To add someone, open their record under Teachers.
   */
  staff?: {
    docs?: (number | Teacher)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StaffListBlock".
 */
export interface StaffListBlock {
  /**
   * Shown to the left of the content. Leave empty and the section spans the full page width.
   */
  label?: string | null;
  /**
   * The two contextual options build the list from appointments — add one to a person and they appear here.
   */
  source?: ('manual' | 'institute' | 'department') | null;
  /**
   * Pick from the teacher directory. Cards show in the order added — drag to reorder. The position comes from the person's appointment, so it can differ between pages.
   */
  people?: (number | Teacher)[] | null;
  /**
   * "Grid" — four even columns. "Carousel" — scrolls sideways. "Rows" — one under another. "Compact" — names and positions only.
   */
  variant: 'grid' | 'carousel' | 'rows' | 'compact';
  /**
   * How many cards show before "See more". Empty shows everyone at once.
   */
  initialVisible?: number | null;
  /**
   * Automatic: two columns with a heading, full width without one. "In the text column": when the block continues the section above and has no heading of its own.
   */
  width?: ('auto' | 'content' | 'full') | null;
  /**
   * Visitors can collapse and expand this section by clicking its heading.
   */
  collapsible?: boolean | null;
  /**
   * The section stays collapsed until a visitor clicks its heading.
   */
  collapsedByDefault?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'staffList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  /**
   * Shown to the left of the content. Leave empty and the section spans the full page width.
   */
  label?: string | null;
  address?: string | null;
  email?: string | null;
  phones?:
    | {
        number: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  socials?:
    | {
        platform: 'facebook' | 'instagram' | 'youtube' | 'telegram' | 'whatsapp' | 'linkedin' | 'x';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Automatic: two columns with a heading, full width without one. "In the text column": when the block continues the section above and has no heading of its own.
   */
  width?: ('auto' | 'content' | 'full') | null;
  /**
   * Visitors can collapse and expand this section by clicking its heading.
   */
  collapsible?: boolean | null;
  /**
   * The section stays collapsed until a visitor clicks its heading.
   */
  collapsedByDefault?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Submissions from the public /submit form. The file is generated automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  department: string;
  fullName: string;
  position?: string | null;
  degree?: string | null;
  academicTitle?: string | null;
  /**
   * ID or full URL
   */
  orcid?: string | null;
  /**
   * ID or full URL
   */
  scopus?: string | null;
  /**
   * ID or full URL
   */
  wos?: string | null;
  /**
   * ID or full URL
   */
  googleScholar?: string | null;
  email: string;
  bio?: string | null;
  publications?:
    | {
        entry?: string | null;
        id?: string | null;
      }[]
    | null;
  projects?:
    | {
        entry?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Checked when the document was emailed. Unchecked when SMTP is not configured or the send failed.
   */
  emailSent?: boolean | null;
  /**
   * Link to the generated .docx — opens while signed in to the admin panel.
   */
  fileUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'institutes';
        value: number | Institute;
      } | null)
    | ({
        relationTo: 'departments';
        value: number | Department;
      } | null)
    | ({
        relationTo: 'teachers';
        value: number | Teacher;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutes_select".
 */
export interface InstitutesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortName?: T;
  order?: T;
  image?: T;
  homepageImage?: T;
  about?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        pullQuote?: T | PullQuoteBlockSelect<T>;
        videoEmbed?: T | VideoEmbedBlockSelect<T>;
        pillLinks?: T | PillLinksBlockSelect<T>;
        statsBand?: T | StatsBandBlockSelect<T>;
        personCard?: T | PersonCardBlockSelect<T>;
        staffList?: T | StaffListBlockSelect<T>;
        contactBlock?: T | ContactBlockSelect<T>;
      };
  contacts?:
    | T
    | {
        address?: T;
        room?: T;
        phone?: T;
        email?: T;
      };
  departments?: T;
  staff?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  label?: T;
  content?: T;
  width?: T;
  collapsible?: T;
  collapsedByDefault?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PullQuoteBlock_select".
 */
export interface PullQuoteBlockSelect<T extends boolean = true> {
  label?: T;
  text?: T;
  attribution?: T;
  width?: T;
  collapsible?: T;
  collapsedByDefault?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock_select".
 */
export interface VideoEmbedBlockSelect<T extends boolean = true> {
  label?: T;
  url?: T;
  title?: T;
  width?: T;
  collapsible?: T;
  collapsedByDefault?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PillLinksBlock_select".
 */
export interface PillLinksBlockSelect<T extends boolean = true> {
  label?: T;
  source?: T;
  items?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              reference?: T;
              url?: T;
              anchor?: T;
              newTab?: T;
            };
        id?: T;
      };
  width?: T;
  collapsible?: T;
  collapsedByDefault?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBandBlock_select".
 */
export interface StatsBandBlockSelect<T extends boolean = true> {
  label?: T;
  source?: T;
  stats?:
    | T
    | {
        value?: T;
        caption?: T;
        id?: T;
      };
  width?: T;
  collapsible?: T;
  collapsedByDefault?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PersonCardBlock_select".
 */
export interface PersonCardBlockSelect<T extends boolean = true> {
  label?: T;
  teacher?: T;
  width?: T;
  collapsible?: T;
  collapsedByDefault?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StaffListBlock_select".
 */
export interface StaffListBlockSelect<T extends boolean = true> {
  label?: T;
  source?: T;
  people?: T;
  variant?: T;
  initialVisible?: T;
  width?: T;
  collapsible?: T;
  collapsedByDefault?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  label?: T;
  address?: T;
  email?: T;
  phones?:
    | T
    | {
        number?: T;
        label?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  width?: T;
  collapsible?: T;
  collapsedByDefault?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  institute?: T;
  order?: T;
  externalUrl?: T;
  image?: T;
  head?: T;
  about?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        pullQuote?: T | PullQuoteBlockSelect<T>;
        videoEmbed?: T | VideoEmbedBlockSelect<T>;
        pillLinks?: T | PillLinksBlockSelect<T>;
        statsBand?: T | StatsBandBlockSelect<T>;
        personCard?: T | PersonCardBlockSelect<T>;
        staffList?: T | StaffListBlockSelect<T>;
        contactBlock?: T | ContactBlockSelect<T>;
      };
  research?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        pullQuote?: T | PullQuoteBlockSelect<T>;
        videoEmbed?: T | VideoEmbedBlockSelect<T>;
        pillLinks?: T | PillLinksBlockSelect<T>;
        statsBand?: T | StatsBandBlockSelect<T>;
        personCard?: T | PersonCardBlockSelect<T>;
        staffList?: T | StaffListBlockSelect<T>;
        contactBlock?: T | ContactBlockSelect<T>;
      };
  clubs?:
    | T
    | {
        name?: T;
        description?: T;
        supervisor?: T;
        id?: T;
      };
  labs?:
    | T
    | {
        name?: T;
        description?: T;
        image?: T;
        equipment?: T;
        id?: T;
      };
  contacts?:
    | T
    | {
        address?: T;
        room?: T;
        phone?: T;
        email?: T;
      };
  staff?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers_select".
 */
export interface TeachersSelect<T extends boolean = true> {
  fullName?: T;
  slug?: T;
  photo?: T;
  degree?: T;
  email?: T;
  appointments?:
    | T
    | {
        unit?: T;
        position?: T;
        isPrimary?: T;
        order?: T;
        id?: T;
      };
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        portrait?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  department?: T;
  fullName?: T;
  position?: T;
  degree?: T;
  academicTitle?: T;
  orcid?: T;
  scopus?: T;
  wos?: T;
  googleScholar?: T;
  email?: T;
  bio?: T;
  publications?:
    | T
    | {
        entry?: T;
        id?: T;
      };
  projects?:
    | T
    | {
        entry?: T;
        id?: T;
      };
  emailSent?: T;
  fileUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}